server:
  port: 8080
spring:
  application:
    name: whim
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  profiles:
    active: ${PROFILES_ACTIVE:dev}